std_msgs/Header header

float32 t_preprocess
float32 t_preprocess1
float32 t_preprocess2
float32 t_preprocess3
float32 t_get_factors
float32 t_update_map
float32 t_insertion

int32 n_unprocessed
int32 n_rejected_insufficient_corres_points
int32 n_rejected_max_corres_dist
int32 n_rejected_eigensolver_fail
int32 n_rejected_min_eigen_value_low
int32 n_rejected_line
int32 n_rejected_plane
int32 n_rejected_max_error
int32 n_correspondances

int32 n_linearize_calls

int32 n_points_in
int32 n_points_in_ss_ds
int32 n_points_in_sm_ds

float32[3] localizability_trans_comp
float32[3] localizability_rot_comp
float32[3] localizability_trans_final
float32[3] localizability_rot_final

float32[3] degen_trans_val
float32[3] degen_rot_val
int32[3] degen_trans_bool
int32[3] degen_rot_bool
